### ISSUE TITLE
Problema conectando la base de datos al servidor

### ISSUE THREAD

**Issue by tnazal99** [IIC2413/Syllabus-2023-2#208]
Al intentar conectar la base de datos al servidor, al ser utilizada por una consulta por ejemplo, recibimos el siguiente error.

error_reporting(E_ALL); No se pudo conectar a la base de datos: PDOException: SQLSTATE[08006] [7] connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL: password authentication failed for user "grupo16" connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL: password authentication failed for user "grupo16" in /home/grupo16/Sites/config/conexion.php:6 Stack trace: #0 /home/grupo16/Sites/config/conexion.php(6): PDO->__construct() #1 /home/grupo16/Sites/consultas/consulta_1.php(11): require('...') #2 {main}

La clave que se espera es la misma que ocupamos para nuestro user en FileZilla? O hay una clave general?

**Comment by LucasReds** [comment]
A mi me pasa algo parecido:

No se pudo conectar a la base de datos: PDOException: SQLSTATE[08006] [7] connection to server at "bachman.ing.puc.cl" (146.155.13.54), port 22 failed: server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request. SSL SYSCALL error: Connection reset by peer connection to server at "bachman.ing.puc.cl" (146.155.13.54), port 22 failed: expected authentication request from server, but received S in /home/grupo75/Sites/config/conexion.php:6 Stack trace: #0 /home/grupo75/Sites/config/conexion.php(6): PDO->__construct() #1 /home/grupo75/Sites/consultas/consulta_1.php(6): require('...') #2 {main}

**Comment by solebravo** [comment]
Nosotros tenemos el siguiente error
![2C79AFFF-8C89-4F32-ADC9-ED4CAF212508](https://github.com/IIC2413/Syllabus-2023-2/assets/106562597/226e93e6-b362-4c0d-a6d4-fca29ce0fcb3)

**Comment by Paldana99** [comment]
El error de @tnazal99 se debe a la contraseña incorrecta.
Los de @LucasReds @solebravo sigue persistiendo el error?

**Comment by blampasona18** [comment]
Hola yo estoy con este mismo error
![image](https://github.com/IIC2413/Syllabus-2023-2/assets/114322883/bf001d10-bca5-40c6-a4ae-1c45cc970fad)
